method: hsv

preprocessing:
  blur:
    type: none
    kernel_size: 5
    sigma_x: 0

  clahe:
    enabled: false
    clip_limit: 2.0
    tile_grid_size: 8

hsv:
  #ranges listed in hsv format. H:[0, 179], S: [0, 255], V: [0, 255]
  ranges:
    #green
    - lower: [70, 110, 80]
      upper: [85, 255, 255]
    
    #red
    - lower: [0, 150, 65]
      upper: [5, 255, 255]
    - lower: [177, 210, 150]
      upper: [179, 255, 255]
    
    #blue
    - lower: [100, 240, 110]
      upper: [105, 255, 255]

    #yellow
    - lower: [21, 200, 160]
      upper: [26, 255, 255]

    #white
    #- lower: [0, 0, 200]
    #  upper: [179, 50, 255]

    #orange
    - lower: [10, 240, 140]
      upper: [15, 255, 255]

    #pink
    - lower: [170, 60, 160]
      upper: [175, 255, 255]
    
    #cyan
    - lower: [87, 90, 120]
      upper: [93, 255, 255]

    #lime green
    - lower: [32, 215, 130]
      upper: [37, 240, 255]

morphology:
  open_kernel_size: 5
  open_iterations: 3
  close_kernel_size: 5
  close_iterations: 3

contour:
  min_area: 150
  min_circularity: 0.3